# Generated by Django 3.0.3 on 2020-03-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
